# Generated by Django 4.2 on 2023-07-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD_Attribute',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='BannerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_category', to='advertisement.category')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_tm', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image_desktop', models.ImageField(upload_to='banners/')),
                ('image_mobile', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_banner', to='advertisement.bannertype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('price', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ads', to='advertisement.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_advertisement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('common.commonmodel',),
        ),
        migrations.CreateModel(
            name='AD_Comment',
            fields=[
                ('commentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commentmodel')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_comment', to='advertisement.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement Comment',
                'verbose_name_plural': 'Advertisement Comments',
            },
            bases=('common.commentmodel',),
        ),
        migrations.CreateModel(
            name='AD_Attribute_Value',
            fields=[
                ('attribute_values_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attribute_values')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atvertisement_attr_value', to='advertisement.advertisement')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_attr', to='advertisement.ad_attribute')),
            ],
            bases=('common.attribute_values',),
        ),
    ]
