# Generated by Django 4.2 on 2023-07-21 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad_attribute',
            options={'verbose_name': 'Bildiriş atribýut', 'verbose_name_plural': 'Bildiriş atribýutlar'},
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bildiriş', 'verbose_name_plural': 'Bildirişler'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='bannertype',
            options={'verbose_name': 'Banner Görnüşi', 'verbose_name_plural': 'Banner Görnüşleri'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriýa', 'verbose_name_plural': 'Kategoriýalar'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Içki kategoriýa', 'verbose_name_plural': 'Içki kategoriýalar'},
        ),
        migrations.AlterField(
            model_name='ad_attribute_value',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atvertisement_attr_value', to='advertisement.advertisement', verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='ad_attribute_value',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_attr', to='advertisement.ad_attribute', verbose_name='Attribýut'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ads', to='advertisement.subcategory', verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(default=0, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_advertisement', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_desktop',
            field=models.ImageField(upload_to='banners/', verbose_name='Surat Uly'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(upload_to='banners/', verbose_name='Surat kiçi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiwmy?'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle (en)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle (ru)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_tm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle (tm)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady (en)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady (ru)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_tm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady (tm)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_banner', to='advertisement.bannertype', verbose_name='Banner görnüşi'),
        ),
        migrations.AlterField(
            model_name='bannertype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_category', to='advertisement.category', verbose_name='Esasy kategoriýa'),
        ),
    ]
