# Generated by Django 4.2 on 2023-07-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0002_alter_ad_attribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad_attribute_value',
            options={'verbose_name': 'Bildiriş Atr Bahasy', 'verbose_name_plural': 'Bildiriş Attr Bahalary'},
        ),
        migrations.AlterModelOptions(
            name='ad_comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Advertisement Comment', 'verbose_name_plural': 'Advertisement Comments'},
        ),
        migrations.AlterField(
            model_name='ad_comment',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_comment', to='advertisement.advertisement', verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='ad_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
    ]
