# Generated by Django 4.2 on 2023-07-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_ad_attribute_value_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.subcategory', verbose_name='Kategoriýa'),
        ),
    ]
