from django.urls import path

from . import views

urlpatterns = [
    path('vehicle-type-list/', views.VehicleTypeList.as_view(),
         name="vehicle-type-list"),
    path('cargo-type-list/', views.CargoTypeList.as_view(),
         name="cargo-type-list"),
    path('warehouse-type-list/', views.WarehouseTypeList.as_view(),
         name="warehouse-type-list"),
    path('driver-attr-list/', views.DriverAttributesList.as_view(),
         name="driver-attr-list"),
    path('cargo-attr-list/', views.CargoAttributesList.as_view(),
         name="cargo-attr-list"),
    path('warehouse-attr-list/', views.WarehouseAttributesList.as_view(),
         name="warehouse-attr-list"),
    path('transport-attr-list/', views.TransportAttributesList.as_view(),
         name="transport-attr-list"),
    path('drivers-list/', views.DriverList.as_view(), name='drivers-list'),
    path('driver-detail/<int:pk>/', views.DriverDetailView.as_view(),
         name="driver-detail"),
    path('driver-create/', views.DriverCreate.as_view(),
         name='driver-create'),
    path('driver-update/<int:pk>/', views.DriverUpdate.as_view(),
         name='driver-update'),
    path('driver-delete/<int:pk>/', views.DriverDelete.as_view(),
         name='driver-delete'),
    path('driver-attr-value-create/', views.DriverAttrValueCreate.as_view(),
         name='driver-attr-value-create'),
    path('driver-attr-value-update/<int:pk>/', views.DriverAttrValueUpdate.as_view(),
         name='driver-attr-value-update'),
    path('driver-attr-value-delete/<int:pk>/', views.DriverAttrValueDelete.as_view(),
         name='driver-attr-value-delete'),
    path('driver-comment-create/', views.DriverCommentCreate.as_view(),
         name='driver-comment-create'),
    path('driver-comment-update/<int:pk>/', views.DriverCommentUpdate.as_view(),
         name='driver-comment-update'),
    path('driver-comment-delete/<int:pk>/', views.DriverCommentDelete.as_view(),
         name='driver-comment-delete'),
    path('driver-rate/<int:pk>/', views.DriverRatingCreate.as_view(),
         name='driver-rate'),
    path('driver-seen-count/<int:pk>/', views.DriverSeenCount.as_view(),
         name='driver-seen-count'),
    path('driver-like-count-add/<int:pk>/', views.DriverLikeCountAdd.as_view(),
         name='driver-like-count-add'),
    path('driver-like-count-remove/<int:pk>/', views.DriverLikeCountRemove.as_view(),
         name='driver-like-count-remove'),
    path('carg-list/', views.CargoList.as_view(), name='cargo-list'),
    path('carg-detail/<int:pk>/', views.CargoDetailView.as_view(), name='cargo-list'),
    path('cargo-create/', views.CargoCreate.as_view(), name='cargo-create'),
    path('cargo-update/<int:pk>/', views.CargoUpdate.as_view(), name='cargo-update'),
    path('cargo-attr-value-create/', views.CargoAttrValueCreate.as_view(),
         name='cargo-attr-value-create'),
    path('cargo-attr-value-update/<int:pk>/', views.CargoAttrValueUpdate.as_view(),
         name='cargo-attr-value-update'),
    path('cargo-attr-value-delete/<int:pk>/', views.CargoAttrValueDelete.as_view(),
         name='cargo-attr-value-delete'),
    path('cargo-comment-create/', views.CargoCommentCreate.as_view(),
         name='cargo-comment-create'),
    path('cargo-comment-update/<int:pk>/', views.CargoCommentUpdate.as_view(),
         name='cargo-comment-update'),
    path('cargo-comment-delete/<int:pk>/', views.CargoCommentDelete.as_view(),
         name='cargo-comment-delete'),
    path('cargo-rate/<int:pk>/', views.CargoRatingCreate.as_view(),
         name='cargo-rate'),
    path('cargo-seen-count/<int:pk>/', views.CargoSeenCount.as_view(),
         name='cargo-seen-count'),
    path('cargo-like-add/<int:pk>/', views.CargoLikeCountAdd.as_view(),
         name='cargo-like-add'),
    path('cargo-like-remove/<int:pk>/', views.CargoLikeCountRemove.as_view(),
         name='cargo-like-remove'),
    path('wharehouse-list/', views.WarehouseList.as_view(), name='warehouse-list'),
    path('warehouse-detail/<int:pk>/', views.WarehouseDetailView.as_view(),
         name='warehouse-detail'),
    path('warehouse-create/', views.WarehouseCreate.as_view(),
         name='warehouse-create'),
    path('warehouse-update/<int:pk>/', views.WarehouseUpdate.as_view(),
         name='warehouse-update'),
    path('warehouse-delete/<int:pk>/', views.WarehouseDelete.as_view(),
         name='warehouse-delete'),
    path('warehouse-attr-value-create/', views.WarehouseAttrValueCreate.as_view(),
         name='warehouse-attr-value-create'),
    path('warehouse-attr-value-update/<int:pk>/', views.WarehouseAttrValueUpdate.as_view(),
         name='warehouse-attr-value-update'),
    path('warehouse-attr-value-delete/<int:pk>/', views.WarehouseAttrValueDelete.as_view(),
         name='warehouse-attr-value-delete'),
    path('warehouse-comment-create/', views.WarehouseCommentCrate.as_view(),
         name='warehouse-comment-create'),
    path('warehouse-comment-update/<int:pk>/', views.WarehouseCommentUpdate.as_view(),
         name='warehouse-comment-update'),
    path('warehouse-comment-delete/<int:pk>/', views.WarehouseCommentDelete.as_view(),
         name='warehouse-comment-delete'),
    path('warehouse-rate/<int:pk>/', views.WarehouseRatingCreate.as_view(),
         name='warehouse-rate'),
    path('warehouse-seen-count/<int:pk>/', views.WarehouseSeenCount.as_view(),
         name='warehouse-seen-count'),
    path('warehouse-like-count-add/<int:pk>/', views.WarehouseLikeCountAdd.as_view(),
         name='warehouse-like-count-add'),
    path('warehouse-like-count-remove/<int:pk>/', views.WarehouseLikeCountRemove.as_view(),
         name='warehouse-like-count-remove'),
    path('transport-list/', views.TransportList.as_view(), name='transport-list'),
    path('transport-detail/<int:pk>/', views.TransportDetailView.as_view(),
         name='transport-detail'),
    path('transport-create/', views.TransportCreate.as_view(), name='transport-create'),
    path('transport-update/<int:pk>/', views.TransportUpdate.as_view(), name='transport-update'),
    path('transport-delete/<int:pk>/', views.TransportDelete.as_view(), name='transport-delete'),
    path('transport-attr-value-create/', views.TransportAttrValueCreate.as_view(),
         name='transport-attr-value-create'),
    path('transport-attr-value-update/<int:pk>/', views.TransportAttrValueUpdate.as_view(),
         name='transport-attr-value-update'),
    path('transport-attr-value-delete/<int:pk>/', views.TransportAttrValueDelete.as_view(),
         name='transort-attr-value-delete'),
    path('transport-comment-create/', views.TransportCommentCreate.as_view(),
         name='transport-comment-create'),
    path('transport-comment-update/<int:pk>/', views.TransportCommentUpdate.as_view(),
         name='transport-comment-update'),
    path('transport-comment-delete/<int:pk>/', views.TransportCommentDelete.as_view(),
         name='transport-comment-delete'),
    path('transport-rate/<int:pk>/', views.TransportRatingCreate.as_view(),
         name='transport-reate'),
    path('transport-seen-count/<int:pk>/', views.TransportSeenCount.as_view(),
         name='transport-seen-count'),
    path('transport-like-count-add/<int:pk>/', views.TransportLikeCountAdd.as_view(),
         name='transport-like-count-add'),
    path('transport-like-count-remove/<int:pk>/', views.TransportLikeCountRemove.as_view(),
         name='transport-like-count-remove'),
]