from django.urls import path

from . import views

urlpatterns = [
    path('vehicle-type-list/', views.VehicleTypeList.as_view(),
         name="vehicle-type-list"),
    path('cargo-type-list/', views.CargoTypeList.as_view(),
         name="cargo-type-list"),
    path('warehouse-type-list/', views.WarehouseTypeList.as_view(),
         name="warehouse-type-list"),
    path('driver-attr-list/', views.DriverAttributesList.as_view(),
         name="driver-attr-list"),
    path('cargo-attr-list/', views.CargoAttributesList.as_view(),
         name="cargo-attr-list"),
    path('warehouse-attr-list/', views.WarehouseAttributesList.as_view(),
         name="warehouse-attr-list"),
    path('transport-attr-list/', views.TransportAttributesList.as_view(),
         name="transport-attr-list"),
    path('drivers-list/', views.DriverList.as_view(), name='drivers-list'),
    path('driver-detail/<int:pk>/', views.DriverDetailView.as_view(),
         name="driver-detail"),
    path('driver-create/', views.DriverCreate.as_view(),
         name='driver-create'),
    path('driver-update/<int:pk>/', views.DriverUpdate.as_view(),
         name='driver-update'),
    path('driver-delete/<int:pk>/', views.DriverDelete.as_view(),
         name='driver-delete'),
    path('driver-attr-value-create/', views.DriverAttrValueCreate.as_view(),
         name='driver-attr-value-create'),
    path('driver-attr-value-update/<int:pk>/', views.DriverAttrValueUpdate.as_view(),
         name='driver-attr-value-update'),
    path('driver-attr-value-delete/<int:pk>/', views.DriverAttrValueDelete.as_view(),
         name='driver-attr-value-delete'),
    path('driver-comment-create/', views.DriverCommentCreate.as_view(),
         name='driver-comment-create'),
    path('driver-comment-update/<int:pk>/', views.DriverCommentUpdate.as_view(),
         name='driver-comment-update'),
    path('driver-comment-delete/<int:pk>/', views.DriverCommentDelete.as_view(),
         name='driver-comment-delete'),
    path('driver-rate/<int:pk>/', views.DriverRatingCreate.as_view(),
         name='driver-rate'),
    path('driver-seen-count/<int:pk>/', views.DriverSeenCount.as_view(),
         name='driver-seen-count'),
    path('driver-like-count-add/<int:pk>/', views.DriverLikeCountAdd.as_view(),
         name='driver-like-count-add'),
    path('driver-like-count-remove/<int:pk>/', views.DriverLikeCountRemove.as_view(),
         name='driver-like-count-remove'),
    path('carg-list/', views.CargoList.as_view(), name='cargo-list'),
]