# Generated by Django 4.2 on 2023-07-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('from_country', models.CharField(blank=True, max_length=255, null=True)),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_country', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('loading_date', models.DateField(blank=True, null=True)),
                ('unloading_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('common.commonmodel',),
        ),
        migrations.CreateModel(
            name='CargoAttribute',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('common.commonmodel',),
        ),
        migrations.CreateModel(
            name='Driver_Attribute',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('is_local', models.BooleanField(default=False)),
                ('from_country', models.CharField(blank=True, max_length=255, null=True)),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_country', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transport', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('common.commonmodel',),
        ),
        migrations.CreateModel(
            name='TransportAttribute',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('capasity', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_warehouse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('common.commonmodel',),
        ),
        migrations.CreateModel(
            name='WarehouseAttribute',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='WarehouseAttributeValue',
            fields=[
                ('attribute_values_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attribute_values')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_warehouse_attr_value', to='service.warehouseattribute')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_warehouse_attr_value', to='service.warehouse')),
            ],
            bases=('common.attribute_values',),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_type_warehouse', to='service.warehousetype'),
        ),
        migrations.CreateModel(
            name='TransportAttributeValue',
            fields=[
                ('attribute_values_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attribute_values')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_transport_attr_value', to='service.transportattribute')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_transport_attr_value', to='service.transport')),
            ],
            bases=('common.attribute_values',),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_transport', to='service.vehicletype'),
        ),
        migrations.CreateModel(
            name='DriverComment',
            fields=[
                ('commentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commentmodel')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_comment', to='service.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver_comment', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('common.commentmodel',),
        ),
        migrations.CreateModel(
            name='Driver_Attribute_Value',
            fields=[
                ('attribute_values_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attribute_values')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_driver_attr_value', to='service.driver_attribute')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_attr_value', to='service.driver')),
            ],
            bases=('common.attribute_values',),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_driver', to='service.vehicletype'),
        ),
        migrations.CreateModel(
            name='CargoComment',
            fields=[
                ('commentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commentmodel')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_cargo_comment', to='service.cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cargo_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('common.commentmodel',),
        ),
        migrations.CreateModel(
            name='CargoAttributeValue',
            fields=[
                ('attribute_values_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attribute_values')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_cargo_attribute_value', to='service.cargoattribute')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_cargo_attribute_value', to='service.cargo')),
            ],
            bases=('common.attribute_values',),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_type_cargo', to='service.cargotype'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_cargo', to='service.vehicletype'),
        ),
    ]
