# Generated by Django 4.2 on 2023-07-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('common.commonmodel',),
        ),
        migrations.CreateModel(
            name='Driver_Attribute',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attributes')),
            ],
            bases=('common.attributes',),
        ),
        migrations.CreateModel(
            name='DriverComment',
            fields=[
                ('commentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commentmodel')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_comment', to='service.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver_comment', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('common.commentmodel',),
        ),
        migrations.CreateModel(
            name='Driver_Attribute_Value',
            fields=[
                ('attribute_values_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.attribute_values')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_driver_attr_value', to='service.driver_attribute')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_attr_value', to='service.driver')),
            ],
            bases=('common.attribute_values',),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_driver', to='service.vehicletype'),
        ),
    ]
