# Generated by Django 4.2 on 2023-07-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kargo', 'verbose_name_plural': 'Kargolar'},
        ),
        migrations.AlterModelOptions(
            name='cargoattributevalue',
            options={'verbose_name': 'Kargo Atr Bahasy', 'verbose_name_plural': 'Kargo Atr Bahalary'},
        ),
        migrations.AlterModelOptions(
            name='cargocomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kargo Teswir', 'verbose_name_plural': 'Kargo Teswirler'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sürüji', 'verbose_name_plural': 'Sürüjiler'},
        ),
        migrations.AlterModelOptions(
            name='driver_attribute',
            options={'verbose_name': 'Sürüji Atribýut', 'verbose_name_plural': 'Sürüji Atribýutlar'},
        ),
        migrations.AlterModelOptions(
            name='driver_attribute_value',
            options={'verbose_name': 'Sürüji Atribýut Bahasy', 'verbose_name_plural': 'Sürüji Atribýut Bahalary'},
        ),
        migrations.AlterModelOptions(
            name='drivercomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sürüji Teswir', 'verbose_name_plural': 'Sürüji Teswirler'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ulag', 'verbose_name_plural': 'Ulaglar'},
        ),
        migrations.AlterModelOptions(
            name='transportattribute',
            options={'verbose_name': 'Ulag Atribýut', 'verbose_name_plural': 'Ulag Atribýutlar'},
        ),
        migrations.AlterModelOptions(
            name='transportattributevalue',
            options={'verbose_name': 'Ulag atr Bahasy', 'verbose_name_plural': 'Ulag atr Bahalar'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ammar', 'verbose_name_plural': 'Ammarlar'},
        ),
        migrations.AlterModelOptions(
            name='warehouseattribute',
            options={'verbose_name': 'Ammar Atribýut', 'verbose_name_plural': 'Ammar Atribýutlar'},
        ),
        migrations.AlterModelOptions(
            name='warehouseattributevalue',
            options={'verbose_name': 'Ammar', 'verbose_name_plural': 'Ammarlar'},
        ),
        migrations.AlterModelOptions(
            name='warehousetype',
            options={'verbose_name': 'Ammar görnüşi', 'verbose_name_plural': 'Ammar görnüşler'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_type_cargo', to='service.cargotype', verbose_name='Ýük görnüşi'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='from_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Haýsy Ýurtdan'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ýerleşýän ýerden'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='loading_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ýüklenilýän wagty'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='to_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Haýsy Ýurda'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ýerleşýän ýere'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='unloading_date',
            field=models.DateField(blank=True, null=True, verbose_name='Düşürilýän wagty'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_cargo', to='service.vehicletype', verbose_name='Ulag görnüşi'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Göwrümi'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Agramy'),
        ),
        migrations.AlterField(
            model_name='cargoattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_cargo_attribute_value', to='service.cargoattribute', verbose_name='Atribýut'),
        ),
        migrations.AlterField(
            model_name='cargoattributevalue',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_cargo_attribute_value', to='service.cargo', verbose_name='Ýük'),
        ),
        migrations.AlterField(
            model_name='cargocomment',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_cargo_comment', to='service.cargo', verbose_name='Ýük'),
        ),
        migrations.AlterField(
            model_name='cargocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cargo_comment', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_driver', to='service.vehicletype', verbose_name='Ulag görnüşi'),
        ),
        migrations.AlterField(
            model_name='driver_attribute_value',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_driver_attr_value', to='service.driver_attribute', verbose_name='Attribýut'),
        ),
        migrations.AlterField(
            model_name='driver_attribute_value',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_attr_value', to='service.driver', verbose_name='Sürüji'),
        ),
        migrations.AlterField(
            model_name='drivercomment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_comment', to='service.driver', verbose_name='Sürüji'),
        ),
        migrations.AlterField(
            model_name='drivercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver_comment', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sene'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='from_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Haýsy ýurtdan'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ýerleşýän ýerden'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='is_local',
            field=models.BooleanField(default=False, verbose_name='Ýerlimi?'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='to_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Haýsy ýurda'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ýerleşýän ýerden'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transport', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_transport', to='service.vehicletype', verbose_name='Ulag görnüşi'),
        ),
        migrations.AlterField(
            model_name='transportattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_transport_attr_value', to='service.transportattribute', verbose_name='Atribýut'),
        ),
        migrations.AlterField(
            model_name='transportattributevalue',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_transport_attr_value', to='service.transport', verbose_name='Ulag'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='capasity',
            field=models.FloatField(blank=True, null=True, verbose_name='Göwrümi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ýurdy'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Elýeterlimi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ýerleşýän ýeri'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_warehouse', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_type_warehouse', to='service.warehousetype', verbose_name='Sklad görnüşi'),
        ),
        migrations.AlterField(
            model_name='warehouseattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_warehouse_attr_value', to='service.warehouseattribute', verbose_name='Atribýut'),
        ),
        migrations.AlterField(
            model_name='warehouseattributevalue',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_warehouse_attr_value', to='service.warehouse', verbose_name='Ammar'),
        ),
    ]
