# Generated by Django 4.2 on 2023-07-29 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_alter_attribute_values_file_and_more'),
        ('service', '0003_alter_warehouseattributevalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportComment',
            fields=[
                ('commentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commentmodel')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_transport_comment', to='service.transport', verbose_name='Ammar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transport_comment', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy')),
            ],
            options={
                'verbose_name': 'Transport Teswir',
                'verbose_name_plural': 'Transport Teswirler',
                'ordering': ['-created_at'],
            },
            bases=('common.commentmodel',),
        ),
    ]
