# Generated by Django 4.2 on 2023-07-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ba_attribute',
            options={'verbose_name': 'Biznes Akkaunt Atribýut', 'verbose_name_plural': 'Biznes Akkaunt Atribýutlar'},
        ),
        migrations.AlterModelOptions(
            name='ba_attribute_value',
            options={'verbose_name': 'Biznes Akkaunt Atribýut Bahasy', 'verbose_name_plural': 'Biznes Akkaunt Atribýut Bahalary'},
        ),
        migrations.AlterModelOptions(
            name='businessaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Biznes Akkaunt', 'verbose_name_plural': 'Biznes Akkauntrlar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'Ulanyjy', 'verbose_name_plural': 'Ulanyjylar'},
        ),
        migrations.AlterField(
            model_name='ba_attribute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attributes/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='ba_attribute',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Ady (en)'),
        ),
        migrations.AlterField(
            model_name='ba_attribute',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Ady (ru)'),
        ),
        migrations.AlterField(
            model_name='ba_attribute',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='Ady (tm)'),
        ),
        migrations.AlterField(
            model_name='ba_attribute_value',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ba_attr_value', to='user.ba_attribute', verbose_name='Atribýut'),
        ),
        migrations.AlterField(
            model_name='ba_attribute_value',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ba_value', to='user.businessaccount', verbose_name='Biznes Akkaunt'),
        ),
        migrations.AlterField(
            model_name='ba_attribute_value',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attributes/', verbose_name='Faýl'),
        ),
        migrations.AlterField(
            model_name='ba_attribute_value',
            name='value_en',
            field=models.CharField(max_length=255, verbose_name='Baha (en)'),
        ),
        migrations.AlterField(
            model_name='ba_attribute_value',
            name='value_ru',
            field=models.CharField(max_length=255, verbose_name='Baha (ru)'),
        ),
        migrations.AlterField(
            model_name='ba_attribute_value',
            name='value_tm',
            field=models.CharField(max_length=255, verbose_name='Baha (tm)'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Giňişleýin (en)'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Giňişleýin (ru)'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='description_tm',
            field=models.TextField(blank=True, null=True, verbose_name='Giňişleýin (tm)'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='business_file/', verbose_name='Faýl'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='business_img/', verbose_name='Surat 1'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='business_img/', verbose_name='Surat 2'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='business_img/', verbose_name='Surat 3'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='business_img/', verbose_name='Surat 4'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiwmy?'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Tassyklanamy?'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Reýting'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Reýting Sany'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady (en)'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady (ru)'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='title_tm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady (tm)'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_account_user', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ad_count',
            field=models.IntegerField(default=0, verbose_name='Bildiriş sany'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Şäher'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ýurdy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile/', verbose_name='Faýl'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Familiýasy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email tassyklananmy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_verified',
            field=models.BooleanField(default=False, verbose_name='Mobil tassyklananmy'),
        ),
    ]
