# Generated by Django 4.2 on 2023-07-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_ba_attribute_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='seen_count',
            field=models.ImageField(default=0, upload_to='', verbose_name='Görülen Sany'),
        ),
    ]
