# Generated by Django 4.2.3 on 2023-07-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_email_verified_user_mobile_verified_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',)},
        ),
    ]
