# Generated by Django 4.2 on 2023-07-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_businessaccount_seen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='seen_count',
            field=models.IntegerField(default=0, verbose_name='Görülen Sany'),
        ),
    ]
