# Generated by Django 4.2 on 2023-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_businessaccount_seen_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ads_count',
            field=models.IntegerField(default=0, verbose_name='Bildiriş sany'),
        ),
    ]
